name: borafitness-oracle
on: [push]
jobs:
    deploy_to_oracle:
        name: deploy to Oracle Cloud
        runs-on: ubuntu-latest

        steps:
            # Git checkout
            - name: Checkout
              uses: actions/checkout@v2

            - name: list folder
              run: ls -la

            - name: Git Pull
              uses: appleboy/ssh-action@master
              with:
                host: 144.22.209.69
                username: ubuntu
                key: ${{ secrets.SSH_PRIVATE_KEY }}
                port: 22
                script: |
                  cd ~/www.borafitness.com.br
                  git pull
                  sudo cp ~/www.borafitness.com.br/deploy_from_pipe.sh ~/deploy_from_pipe.sh
                  sudo chmod +x ~/deploy_from_pipe.sh
                  bash ~/deploy_from_pipe.sh