name: borafitness-oracle
on: [push]
jobs:
    deploy:
        name: deploy to Oracle Cloud
        runs-on: ubuntu-latest

        steps:
            # Git checkout
            - name: Checkout
              uses: actions/checkout@v2

            - name: list folder
              run: ls -la

            - name: Copy deploy file
              uses: appleboy/scp-action@master
              with:
                host: 144.22.209.69
                username: ubuntu
                key: ${{ secrets.SSH_PRIVATE_KEY }}
                port: 22
                source: "~/www.borafitness.com.br/deploy_from_pipe.sh"
                target: "~/deploy_from_pipe.sh"

            - name: Giving permission
              uses: appleboy/ssh-action@master
              with:
                host: 144.22.209.69
                username: ubuntu
                key: ${{ secrets.SSH_PRIVATE_KEY }}
                port: 22
                script: |
                  sudo chmod +x ~/deploy_from_pipe.sh

            - name: Executar script via SSH
              uses: appleboy/ssh-action@master
              with:
                host: 144.22.209.69
                username: ubuntu
                key: ${{ secrets.SSH_PRIVATE_KEY }}
                port: 22
                script: |
                  bash ~/deploy_from_pipe.sh