name: borafitness-oracle
on: [push]
jobs:
  deploy:
    name: deploy to Oracle Cloud
    runs-on: ubuntu-latest

    steps:
      # Git checkout
      - name: Checkout
        uses: actions/checkout@v2

      # running a teste
      - name: list folder
        run: ls -la
